# Generated by Django 2.2 on 2019-04-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190408_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to='static\\thumbnails'),
        ),
    ]
